module.exports = {
    Swipeable: 'Swipeable',
    DrawerLayout: 'DrawerLayout',
    State: {},
    ScrollView: 'ScrollView',
    Slider: 'Slider',
    Switch: 'Switch',
    TextInput: 'TextInput',
    ToolbarAndroid: 'ToolbarAndroid',
    ViewPagerAndroid: 'ViewPagerAndroid',
    DrawerLayoutAndroid: 'DrawerLayoutAndroid',
    WebView: 'WebView',
    NativeViewGestureHandler: 'NativeViewGestureHandler',
    TapGestureHandler: 'TapGestureHandler',
    FlingGestureHandler: 'FlingGestureHandler',
    ForceTouchGestureHandler: 'ForceTouchGestureHandler',
    LongPressGestureHandler: 'LongPressGestureHandler',
    PanGestureHandler: 'PanGestureHandler',
    PinchGestureHandler: 'PinchGestureHandler',
    RotationGestureHandler: 'RotationGestureHandler',
  };
  